Migrations generation mention for the EVM tutorial
subsquid/docs pull request #138
Opened 2023-01-07 18:29 UTC by abernatskiy

Migrations generation now has to be done by hand. Mentioning that in the EVM tutorial.

	modified:   docs/tutorials/create-an-evm-processing-squid.md

2023-01-10 09:03 UTC, dzhelezov requested changes

2023-01-10 09:03 UTC, dzhelezov commented on docs/tutorials/create-an-evm-processing-squid.md
> +make migration
should it be:
```
rm -rf db/migrations/*.js
make down
make up
npm run build
make migration
```

2023-01-10 19:26 UTC, closed without merging

2023-01-10 19:49 UTC, abernatskiy commented
> Yes, for the case when a change is introduced into an already existing schema. With a new squid `make codegen; make migration suffices`. Let me restructure that fragment a bit and come back.
Upon a closer investigation - no, the two commands do not suffice.

2023-01-10 20:09 UTC, dzhelezov commented
Staking migrations proved to be a bad practice -- any meaningful change will likely require a full resync anyway. So it's almost always a good idea to start from a clean db. The only exception is adding an index

2023-01-11 07:27 UTC, abernatskiy commented
The idea was to update migrations more easily before the first `make up`. But upon a closer look at the behavior of `squid-typeorm-migration generate` I realized that the old migrations would have to be manually removed anyway, so I opted to just give the instructions for a general schema change. See the new PR.